format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$nodejs\
$gcloud\
$cmd_duration\
$line_break\
$jobs\
$character"""

[git_branch]
symbol = " "

[python]
symbol = " "
style = "yellow"

[gcloud]
detect_env_vars = ["CLOUDSDK_ACTIVE_CONFIG_NAME"]
symbol = " "
format = 'on [$symbol$active]($style) '
