tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "fnm"
brew "gh"
brew "git"
brew "mise"
brew "starship"
brew "ripgrep"
brew "fzf"
brew "bat"

# Productivity
cask "1password"
cask "1password-cli"
cask "raycast"
cask "obsidian"
cask "google-chrome"
cask "microsoft-edge"
cask "slack"
cask "zoom"

# Developer Tools & Fonts
cask "visual-studio-code"
cask "github"
cask "warp"
cask "docker"
cask "devpod"
cask "google-cloud-sdk"
cask "font-cascadia-code"
cask "font-cascadia-mono"
cask "font-monaspace"
