set fish_color_autosuggestion    grey
set fish_color_command           purple
set fish_color_comment           yellow
set fish_color_cwd               green
set fish_color_cwd_root          red
set fish_color_end               purple
set fish_color_error             red
set fish_color_escape            normal
set fish_color_history_current   cyan
set fish_color_host              normal
set fish_color_match             cyan
set fish_color_normal            normal
set fish_color_operator          blue
set fish_color_param             blue
set fish_color_quote             green
set fish_color_redirection       cyan
set fish_color_search_match      --background=black
set fish_color_selection         --background=purple
set fish_color_status            red
set fish_color_user              normal
set fish_color_valid_path        --underline
set fish_pager_color_completion  white
set fish_pager_color_description yellow
set fish_pager_color_prefix      green
set fish_pager_color_progress    normal
