#!/usr/bin/env bash

set -e

get_os() {
  local os=""
  local kernelName=""

  kernelName="$(uname -s)"
  if [ "$kernelName" == "Darwin" ]; then
    os="macos"
  elif [ "$kernelName" == "Linux" ]; then
    os="linux"
  else
    os="$kernelName"
  fi

  echo "$os"
}

function install_from() {
  source_dir=$1
  for file in $(find $source_dir -type f); do
    relative_file_path="${file#"${source_dir}"/}"
    target_file="${HOME}/${relative_file_path}"
    target_dir="${target_file%/*}"
    if test ! -d "${target_dir}"; then
      mkdir -p "${target_dir}"
    fi

    echo "-> ${target_file##$HOME/}"
    ln -sf "${file}" "${target_file}"
  done
}

OS="$(get_os)"
DOTFILES_ROOT=$(pwd -P)
DOTFILES_SOURCE="src/common src/$OS"

if [[ "$CLOUD_SHELL" == "true" ]]; then
  DOTFILES_SOURCE+=" src/cloudshell"
fi

for source_dir in $DOTFILES_SOURCE; do
  echo "Installing from $source_dir"
  install_from $DOTFILES_ROOT/$source_dir
done
